#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/vendor/autoload.php')){
    require __DIR__.'/vendor/autoload.php';
}else{
    //If global package, pull composers global autoloader
    require __DIR__.'/../../autoload.php';
}

require 'globals.php';

use Symfony\Component\Console\Application;

if(\App\Configuration\Config::hasEnvFile()){
    $dotenv = new Dotenv\Dotenv(__DIR__, '.env');
    $dotenv->load();
}

$config = new App\Configuration\Config();
$config->updateFromEnvironment();

$application = new Application();

$setupCommand = new \App\Commands\Setup(null, $config);
$hostCommand = new \App\Commands\Host(null, $config);
$vagrantCommand = new \App\Commands\Vagrant(null, $config);
$fileCommand = new \App\Commands\File(null, $config);

$application->add($setupCommand);
$application->add($hostCommand);
$application->add($vagrantCommand);
$application->add($fileCommand);

$application->setDefaultCommand($hostCommand->getName());

$application->run();