#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

require 'globals.php';

use Symfony\Component\Console\Application;

if(\App\Configuration\Config::hasEnvFile()){
    $dotenv = new Dotenv\Dotenv(__DIR__, '.env');
    $dotenv->load();
}

$application = new Application();

$setupCommand = new \App\Commands\Setup();
$hostCommand = new \App\Commands\Host();
$vagrantCommand = new \App\Commands\Vagrant();
$fileCommand = new \App\Commands\File();

$application->add($setupCommand);
$application->add($hostCommand);
$application->add($vagrantCommand);
$application->add($fileCommand);

$application->setDefaultCommand($hostCommand->getName());

$application->run();