#!/usr/bin/env php
<?php
$composerGlobal = false;
$dotEnvDirectory = __DIR__;
$dotEnvFileName = '.env';
if(file_exists(__DIR__.'/vendor/autoload.php')){
    require __DIR__.'/vendor/autoload.php';
}else{
    $composerGlobal = true;
    $dotEnvDirectory = __DIR__.'/../../..';
    $dotEnvFileName = '.homeboy';
    require __DIR__.'/../../autoload.php';
}

require 'globals.php';

use Symfony\Component\Console\Application;

$config = new App\Configuration\Config();
$config->setComposerGlobal($composerGlobal);
$config->setDotEnvDirectory($dotEnvDirectory);
$config->setDotEnvFileName($dotEnvFileName);

if($config->hasDotEnvFile()){
    $dotenv = new Dotenv\Dotenv($dotEnvDirectory, $dotEnvFileName);
    $dotenv->load();
    $config->updateFromEnvironment();
}

$application = new Application();

$setupCommand = new \App\Commands\Setup(null, $config);
$hostCommand = new \App\Commands\Host(null, $config);
$vagrantCommand = new \App\Commands\Vagrant(null, $config);
$fileCommand = new \App\Commands\File(null, $config);

$application->add($setupCommand);
$application->add($hostCommand);
$application->add($vagrantCommand);
$application->add($fileCommand);

$application->setDefaultCommand($hostCommand->getName());

$application->run();